#!/bin/sh -v
# copy files source to buildroot to the fast compile

if [ ! -n "$1" ]; then
    echo "No input ID commit at '\$1'."
	exit 1
fi

sshpass -proot scp ./output/build/wpan-tools-master/examples/af_ieee802154_?? root@$1:/root
sshpass -proot scp ./output/build/wpan-tools-master/examples/af_inet6_?? root@$1:/root
sshpass -proot scp ./output/build/wpan-tools-master/examples/af_packet_?? root@$1:/root
sshpass -proot scp ./output/target/usr/bin/iwpan root@$1:/root
sshpass -proot scp ./output/target/usr/bin/wpan-ping root@$1:/root
