#!/bin/sh -v
# copy files source to buildroot to the fast compile

if [ ! -n "$1" ]; then
    echo "No input ID commit at '\$1'."
	exit 1
fi

sshpass -proot scp ./output/build/lowpan-tools-0.3.1/tests/test? root@$1:/root
sshpass -proot scp ./output/build/lowpan-tools-0.3.1/tests/listen-packet root@$1:/root
sshpass -proot scp ./output/build/lowpan-tools-0.3.1/tests/izlisten root@$1:/root
